CREATE TABLE `support_tickets` (
supportID INT NOT NULL AUTO_INCREMENT PRIMARY,
title VARCHAR(100) NOT NULL ,
user  VARCHAR(200) NOT NULL ,
member VARCHAR(200) NOT NULL,
text TEXT NOT NULL,
timestamp VARCHAR(300) NOT NULL,
status INT NOT NULL,
read INT NOT NULL
);
CREATE TABLE `support_answers` (
supportID INT NOT NULL INDEX,
usera VARCHAR(200) NOT NULL,
userm VARCHAR(200) NOT NULL,
text TEXT NOT NULL,
timestamp VARCHAR(300) NOT NULL
);
CREATE TABLE `news` (
newsID INT NOT NULL AUTO_INCREMENT PRIMARY,
poster VARCHAR(200) NOT NULL,
text TEXT NOT NULL,
timestamp VARCHAR(300) NOT NULL
);